repos:
  - repo: local
    hooks:
      - id: precommit
        name: precommit quality gate
        entry: poetry run ta dev precommit
        language: system
        pass_filenames: false
        stages: [pre-commit]
